version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    ports:
      - 8080:8000
    depends_on:
      - db